name: Build Release Zip

on:
  push:
    tags:
      - 'v*'

jobs:
  zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Prepare plugin folder
        run: |
          mkdir webhookarm
          cp -r *.php readme.txt assets LICENSE webhookarm/

      - name: Zip it
        run: zip -r webhookarm.zip webhookarm

      - name: Upload release asset
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: webhookarm.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
